version: '3.1'
services:
  casdoor:
    restart: always
    image: ${CASDOOR_IMG:-casbin/casdoor}:${CASDOOR_TAG:-latest}
    build:
      context: ./
      dockerfile: Dockerfile
      target: STANDARD
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      RUNNING_IN_DOCKER: "true"
      NO_CREATE_DATABASE: "${NO_CREATE_DATABASE:-}"
    volumes:
      - ${CONF_DIR:-./conf}:/conf/
  db:
    restart: always
    image: mysql:8.0.25
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
    volumes:
      - ${MYSQL_DATA:-/usr/local/docker/mysql}:/var/lib/mysql
